name: hencafe
description: "Price Information"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  spider: ^4.2.2
  http: ^1.0.0
  convert: ^3.0.1
  shared_preferences: ^2.0.17
  dart_jsonwebtoken: ^2.13.0
  flutter_advanced_drawer: ^1.3.6
  url_launcher: ^6.2.6
  custom_date_range_picker: ^1.0.10
  drop_down_list: ^0.0.6
  carousel_slider: ^4.2.1
  text_scroll: ^0.2.0
  webview_flutter: ^4.7.0
  flutter_typeahead: ^5.2.0
  package_info_plus: ^4.0.1
  rename_app: ^1.3.2
  animated_switcher_plus: ^1.1.0
  responsive_builder: ^0.7.0
  intro_slider: ^4.2.1
  rounded_loading_button_plus: ^3.0.1
  pinput: ^5.0.0
  smart_auth: ^3.2.0
  flutter_localization: ^0.3.1
  dob_input_field: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/gifs/
