class AppRoutes {
  const AppRoutes._();

  static const String welcome = 'welcome';
  static const String loginMobile = 'login_mobile';
  static const String loginPin = 'login_pin';
  static const String loginOtp = 'login_otp';
  static const String registerBasicDetails = 'register_basic_details';
  static const String registerCreatePin = 'register_create_pin';
  static const String stateSelection = 'state_selection';
  static const String eggPriceScreen = 'egg_price_screen';
  static const String chickPriceScreen = 'chick_price_screen';
  static const String chickenPriceScreen = 'chicken_price_screen';
  static const String liftingPriceScreen = 'lifting_price_screen';
  static const String companyListScreen = 'company_list_Screen';
  static const String sellersListScreen = 'sellers_list_Screen';
  static const String companyDetailsScreen = 'lifting_details_screen';
  static const String forgotPassword = 'forgot_password';
  static const String verifyOtp = 'verify_otp';
  static const String dashboardScreen = 'dashboard_screen';
  static const String sellEggScreen = 'sell_egg_screen';
  static const String sellChickScreen = 'sell_chick_screen';
  static const String sellChickenScreen = 'sell_chicken_screen';
  static const String sellLiftingScreen = 'sell_Lifting_screen';
  static const String myProfileScreen = 'my_profile_screen';
  static const String addressDetailsScreen = 'address_details_screen';
  static const String uploadFileScreen = 'upload_file_screen';
  static const String saleDetailsScreen = 'sale_details_screen';
  static const String videoPlayerScreen = 'video_player_screen';
  static const String imagePreviewScreen = 'image_preview_screen';
  static const String docPreviewScreen = 'doc_preview_screen';
  static const String createAddressScreen = 'create_address_screen';
  static const String contactUsScreen = 'contact_us_screen';
  static const String changePassword = 'changePassword';
  static const String faqScreen = 'medicine_screen';
  static const String notificationsScreen = 'notifications_screen';
  static const String deleteAccountScreen = 'delete_account_screen';
  static const String referralBonusScreen = 'referral_bonus_screen';
  static const String changeMobileScreen = 'change_mobile_screen';
  static const String updateCompanyDetailsScreen = 'update_company_details_screen';
}
